### ISSUE TITLE
Error: Expression doesn't match annotation

### ISSUE THREAD

**Issue by janski1987** [georgefst/monpad#21]
Hi,
I would first like to thank you for this project. Seems very interesting and I'm excited about its future. I have gotten it working, well sort off. I quite new to Haskell and Dhall so it can very well be that I have something configured incorrectly. I'm hoping that you can help me.

So the error "Error: Expression doesn't match annotation" comes when i start the project. Following lines are as follows:

 elements : …
             { element : < Button : : { buttonData : - { … : … } (a record type)
                                                     + < … : … > (a union type)
                                      , …
                                      }
                         | Slider : : { sliderData : { + axis : …
                                                     , + multiplier : …
                                                     }
                                      , …
                                      }
                         | Stick : : { stickDataX : { + axis : …
                                                    , + multiplier : …
                                                    }
                                     , stickDataY : { + axis : …
                                                    , + multiplier : …
                                                    }
                                     , …
                                     }
                         | …
                         >
             , …
             }
, …
}

    1│ ({ toLinux =
    2│     λ ( e
    3│       : { elements :
    4│             List
    5│               { element :
    6│                   < Button :
    7│                       { buttonData :
    8│                           { linux :
    9│                               < Btn0
   10│                               | Btn1
   11│                               | Btn2
   12│                               | Btn3
   13│                               | Btn4
   14│                               | Btn5
   15│                               | Btn6
   16│                               | Btn7
   17│                               | Btn8
   18│                               | Btn9
   19│                               | BtnA
   20│                               | BtnB
============================================================================
22509│                   , blue : Double
22510│                   , alpha : Double
22511│                   }
22512│               , backgroundColour :
22513│                   { red : Double
22514│                   , green : Double
22515│                   , blue : Double
22516│                   , alpha : Double
22517│                   }
22518│               , vertical : Bool
22519│               , sliderData : {}
22520│               }
22521│           | Image : { width : Natural, height : Natural, url : Text }
22522│           >
22523│       , location : { x : Integer, y : Integer }
22524│       , name : Text
22525│       , showName : Bool
22526│       }
22527│ , viewBox : { x : Integer, y : Integer, w : Integer, h : Integer }
22528│ }

I think it's inferring the contents of buttonData wrongly. I remember that there was in the docs of Dhall, I think. 
The projects starts thou if I add --system-device to the startup command. I hope that you can help me with this. My goal is to use the project to play retrogames in Kodi. I don't have controllers so it would be nice if I can play with my phone instead of a keyboard.

**Comment by georgefst** [comment]
Hi! I'm hoping to get this all more properly documented over the next few months. It's not very user-friendly at the moment, but I'm happy to answer any questions.

It sounds like you probably do want the `--system-device` flag, which, in the case of Linux, actually sets up the virtual input device (using the `evdev`/`uinput` interface). With this flag, the `buttonData` and `stickData` fields need to correspond to evdev keys and axes, respectively.

The fact that this gets rejected without that flag is unfortunate, and is one of the things I want to get fixed upstream before properly releasing the project: #20.

**Comment by georgefst** [comment]
In cf29467, I've changed it so that the system device is set up by default, and there is instead a `--no-system-device` flag to disable it. This is the way it always should have been.

If you pull and rebuild, you'll find that the whole thing builds *a lot* quicker than the first time round.

**Comment by georgefst** [comment]
> My goal is to use the project to play retrogames in Kodi.

Let me know how that goes. It sounds like it should work, but I'm not particularly familiar with Kodi.

**Comment by janski1987** [comment]
Hi
Thank you for the rapid response. Also, thank you for your efforts. I haven't got around to test with the new commit, but I trust you that it's fixed. I'll close this issue.

> Let me know how that goes. It sounds like it should work, but I'm not particularly familiar with Kodi.

Yeah, I will. I just hope I have the time to do it.

All the best, Jan
